In [1]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[arr>30])

[40 50]


In [3]:
import numpy as np
marks=np.array([50,70,90,78,100])
print(marks[marks>45])

[ 50  70  90  78 100]


In [4]:
import numpy as np
arr=np.array([10,20,30,80,79])
print(arr[[0,4]])

[10 79]


In [8]:
arr=np.array([10,20,30,40,50])
for i in range(10,50):
    print(i)

10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


In [9]:
for i in[20,30,94,987]:
    print(i)


20
30
94
987


In [10]:
arr=np.array([1,2,3,4,5,6])
for i in arr:
    print(i)

1
2
3
4
5
6


In [12]:
arr=np.array([[1,2,3,4],[6,7,8,9]])
print(arr)

[[1 2 3 4]
 [6 7 8 9]]


In [13]:
alphabets=np.array([['a','v','g'],['j','f','o'],['d','g','t']])
print(alphabets)

[['a' 'v' 'g']
 ['j' 'f' 'o']
 ['d' 'g' 't']]


In [14]:
alpha=np.array([[1,2,3],[4,7,8],[6,9,0],[4,9,8]])
print(alpha)

[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]


In [18]:
for i in np.nditer(alpha):
 print(alpha)

[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]
[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]
[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]
[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]
[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]
[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]
[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]
[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]
[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]
[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]
[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]
[[1 2 3]
 [4 7 8]
 [6 9 0]
 [4 9 8]]


In [20]:
for i in np.nditer(alpha):
    print(i)

1
2
3
4
7
8
6
9
0
4
9
8


In [24]:
num=([1,2,3,4,5,6])
for i in np.nditer(num):
  print(i)

(array(1), array(2), array(3), array(4), array(5), array(6))


In [27]:
num=([1,2,3])
num1=([7,9,0])
print(num+num1)

[1, 2, 3, 7, 9, 0]


In [54]:
a=(['thar','suzuki'])
b=(['ertiga','ford'])
c=np.array((a+b))
print(c)

['thar' 'suzuki' 'ertiga' 'ford']


In [40]:
a=([1,2,3])
b=([4,3,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 3 6]


In [44]:
arr=np.array([10,20,30,90])
c=np.where((arr==90))
print(c)

(array([3]),)


In [48]:
arr=np.array([10,20,30,90])
c=np.sort((arr))
print(c)

[10 20 30 90]


In [53]:
arr=np.array([10,20,30,90,5,8])
c=np.sort((arr))
print(c)

[ 5  8 10 20 30 90]


In [55]:
a=([1,2,3,4])
b=([8,9,7,6])
c=np.array((a+b))
print(c)

[1 2 3 4 8 9 7 6]


In [61]:
marks=np.array([65,90,87,40,67])
print(marks[marks>40])

[65 90 87 67]


In [62]:
marks=np.max([90,100,30,68])
print(marks)

100


In [63]:
marks=np.sum([5,9,68,93])
print(marks)

175


In [65]:
marks=np.min([9,7,9,29])
print(marks)

7


In [66]:
marks=np.mean([7,9,8,6])
print(marks)

7.5


In [68]:
marks1=np.mean([7,9,0,8])
marks2=np.min([7,9,0,8])
marks3=np.max([7,9,0,8])
marks4=np.average([7,9,0,8])
marks5=np.sum([7,9,0,8])
print(marks1)
print(marks2)
print(marks3)
print(marks4)
print(marks5)

6.0
0
9
6.0
24


In [70]:
marks=np.square([89])
print(marks)

7921


In [79]:
marks=([10,20,30,40])
print(np.power(arr,3))

[  1000   8000  27000 729000    125    512]
